update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots()
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload do
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true, overwrite_screenshots: true)
  end
end
