# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 5s",
#   "iPhone 8 Plus",
#   "iPhone Xs Max",
#   "iPhone Xʀ",
#   "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
  "en-US",
#   "es-ES",
#  "hu-HU",
#   "cs-CZ",
#   "nl-NL",
#  "zh-CN",
#   "fi-FI",
#   "fr-FR",
#   "de-DE",
#  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
