scheme("Screenshots")
clear_previous_screenshots(false)

devices([
  "iPhone 8 Plus",
  "iPhone Xs Max",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
 "en-GB",
 "es-ES",
 "hu",
 "cs",
 "nl-NL",
 "zh-Hans",
 "fi",
 "fr-FR",
 "de-DE",
 "pt-BR"
])
